name: Publish development update

on:
  push:
    branches:
      - main

jobs:
  publish_update:
    name: Publish update to development channel
    type: update
    params:
      channel: development
      message: ${{ github.sha }}
