name: Publish PR update

on:
  pull_request:
    branches: ['*']

jobs:
  publish_update:
    name: Publish update to development channel
    type: update
    params:
      channel: development
      message: ${{ github.sha }}
